/**
 * PHONARA Glossary v14.0 — UI Word Cleaning
 *
 * 5초 룰: 신규 유저가 보면 "여긴 돈 벌고 게임하는 곳" 으로 이해해야 함.
 * 내부 DB 컬럼·내부 코드(empire_levels, crown_events 등)는 그대로,
 * **사용자가 보는 UI 텍스트만** 이 사전을 통해 교체.
 *
 * 사용: import { G } from "@/lib/glossary";  →  <h1>{G.level}</h1>
 */

export const G = {
  // 4탭
  tabEarn: "수익",
  tabGames: "게임",
  tabTrade: "투자",
  tabLive: "실시간",

  // 탭별 한 줄
  tabEarnTagline: "매일 무료로 돈 버는 곳",
  tabGamesTagline: "재미있게 돈 버는 게임",
  tabTradeTagline: "코인으로 스마트하게 돈 벌기",
  tabLiveTagline: "지금 벌고 있는 사람들",

  // 등급/포인트
  level: "레벨",
  bonusPoints: "보너스 포인트",
  vipUpgrade: "VIP 승급",
  vipPass: "VIP 패스",
  seasonSeat: "시즌 좌석",
  weeklyTop: "이번 주 TOP",

  // 활동
  liveBigWin: "실시간 빅윈",
  news: "소식",
  hallOfFame: "명예의 전당",
  guild: "길드",

  // CTA
  ctaStartFree: "지금 무료로 시작",
  ctaStartFreeReward: "+500 보너스 포인트",
  ctaCharge: "충전",
  ctaWithdraw: "출금",
  ctaConvert: "환전",

  // 3대 메시지
  msg1: "무료로 돈 벌 수 있는 곳",
  msg2: "부업하면서 게임도 하고 돈도 버는 곳",
  msg3: "한번 들어오면 헤어나가기 힘든 곳",

  // Earn Hub — v14 Sprint 1
  earnHeader: "오늘 얼마 벌었나요?",
  earnSubheader: "아래만 다 하면 매일 4,000~6,000 PHON 확보",
  earnTodayLabel: "오늘 누적 적립",
  earnFomoLine: "지금도 이웃들이 PHON 받고 있어요",
  earnRouletteTitle: "데일리 무료 룰렛",
  earnRouletteSub: "24시간마다 1회 · 최대 5,000 PHON",
  earnRouletteCta: "오늘의 룰렛 1회 무료",
  earnRouletteDone: "오늘 이미 받았어요",
  earnRouletteSpinning: "돌리는 중…",
  earnRouletteResult: "획득",
  earnRouletteNextIn: "내일 자정 다시 무료",
  earnVipBoostOn: "VIP 부스트 ×1.5 적용중",
  earnVipBoostOff: "VIP 패스로 모든 보상 +50%",
  earnVipBoostCta: "VIP 패스 알아보기",
  earnVipBoostEndsIn: "남은 시간",
  earnShareTitle: "친구한테 자랑하기",
  earnShareSub: "공유 한 번에 +200 PHON",
  earnShareReward: "공유하고 +200 PHON",
  earnShareSheetTitle: "어디로 자랑할까요?",
  earnShareSheetSub: "채널당 1회 · +200 PHON 즉시 적립",
  earnShareCopied: "링크가 복사됐어요",
  earnShareInstagramHint: "이미지를 저장해서 스토리에 올려주세요",
  earnFomoLive: "지금 {n}명이 오늘 PHON 받고 있어요",
  earnVipBoostHint: "모든 미션·룰렛·공유 보상 +50% · 30일 30,000 PHON",

  // Wallet — v14 Sprint 2 (Withdraw UX)
  walletHeader: "내 지갑",
  walletBalance: "내 잔액",
  walletKrwApprox: "약",
  walletTodayEarn: "오늘 적립",
  walletWeekEarn: "이번 주 적립",
  walletAvailable: "출금 가능",
  walletMin: "최소 출금",
  processingBannerTitle: "출금 처리 중",
  processingBannerSub: "보통 5분 안에 도착해요",
  historyTitle: "최근 출금",
  historyEmpty: "아직 출금 내역이 없어요",
  historyStatusPending: "접수됨",
  historyStatusProcessing: "처리 중",
  historyStatusCompleted: "지급 완료",
  historyStatusFailed: "실패",
  withdrawNow: "지금 출금하기",
  withdrawCtaSub: "벌었으면 바로 받으세요",
  withdrawAvgTime: "평균 4분 30초",
  withdrawStep1Title: "얼마 찾을까요?",
  withdrawStep2Title: "어디로 받을까요?",
  withdrawStep3Title: "마지막 확인",
  withdrawAmountLabel: "출금 금액",
  withdrawAllChip: "전액",
  withdrawMethodBank: "계좌이체",
  withdrawMethodCoin: "USDT 출금",
  withdrawMethodGift: "상품권",
  withdrawMethodSoon: "상품권은 입금 전용입니다",
  withdrawPinLabel: "출금 비밀번호 6자리",
  withdrawPinHint: "본인 확인을 위해 PIN을 입력해주세요",
  withdrawConfirmEta: "예상 도착 시간",
  withdrawSubmit: "출금 신청",
  withdrawSuccess: "출금 신청이 접수되었습니다",
  withdrawProcessing: "5분 안에 처리됩니다",
  withdrawErrFrozen: "계정이 일시 동결되었습니다",
  withdrawErrStepUp: "추가 인증이 필요합니다",
  withdrawErrPin: "비밀번호가 일치하지 않습니다",
  withdrawErrMin: "최소 출금 금액 미만입니다",
  withdrawErrFunds: "출금 가능 금액이 부족합니다",
  withdrawErrGeneric: "잠시 후 다시 시도해주세요",
  withdrawNext: "다음",
  withdrawPrev: "이전",
  withdrawClose: "닫기",
  withdrawBankName: "은행",
  withdrawBankAccount: "계좌번호",
  withdrawCoinNetwork: "네트워크",
  withdrawCoinAddress: "지갑 주소",
  withdrawSummaryAmount: "출금 금액",
  withdrawSummaryMethod: "수단",
  withdrawSummaryEta: "예상 도착",
  withdrawEtaWithin5: "5분 이내",
  withdrawPolicyNotice: "출금은 계좌이체 또는 USDT만 가능합니다",

  // Deposit — v14 Sprint 3 (Deposit Fast Lane v3.0)
  depositNow: "지금 충전하기",
  depositCtaSub: "5분 안에 충전 완료",
  depositAvgTime: "평균 5분",
  depositStep1Title: "어떻게 충전할까요?",
  depositStep2Title: "충전 정보 입력",
  depositStep3Title: "충전 신청 완료",
  depositMethodCoin: "USDT 코인",
  depositMethodBank: "계좌이체",
  depositMethodVoucher: "문화상품권",
  depositMethodCoinSub: "1~5분 · 자동 인식",
  depositMethodBankSub: "5~30분 · 자동 매칭",
  depositMethodVoucherSub: "1~6시간 · 수동 확인",
  depositAmountLabel: "충전 금액",
  depositMin: "최소 금액",
  depositCopy: "복사",
  depositCopied: "복사 완료",
  depositCoinNetwork: "네트워크",
  depositCoinAddress: "받는 주소",
  depositCoinUnique: "정확히 이 금액 송금",
  depositCoinExpiresIn: "남은 시간",
  depositCoinWaiting: "입금 대기중 · 송금 즉시 자동 인식",
  depositCoinFilled: "입금 확인 완료",
  depositCoinRegenerate: "다시 만들기",
  depositCoinConfirming: "입금 확인 중입니다",
  depositBankName: "은행",
  depositBankAccount: "입금 계좌",
  depositBankSender: "보내는 분 이름",
  depositBankAutoMatch: "이름이 일치해야 자동 매칭됩니다",
  depositVoucherBrand: "상품권 종류",
  depositVoucherPin: "상품권 PIN (16~18자리)",
  depositVoucherPhoto: "영수증 사진 (선택)",
  depositVoucherKakao: "카톡 채널 1:1로 안내됩니다",
  depositVoucherReview: "수동 확인 중 · 1~6시간",
  depositPolicyNotice: "상품권은 입금 전용입니다 (출금 불가)",
  depositSubmit: "충전 신청",
  depositSuccess: "충전 신청이 접수되었습니다",
  depositEtaCoin: "보통 1~5분 내 반영",
  depositEtaBank: "보통 5~30분 내 반영",
  depositEtaVoucher: "보통 1~6시간 내 반영",
  depositHistoryTitle: "최근 충전",
  depositHistoryEmpty: "아직 충전 내역이 없어요",
  depositHistoryActiveBadge: "진행 중",
  depositSeeMine: "내 충전 보기",
  depositStatusPending: "신청됨",
  depositStatusFilled: "반영완료",
  depositStatusExpired: "만료됨",
  depositStatusReview: "확인 중",
  depositErrMin: "최소 충전 금액 미만입니다",
  depositErrExpired: "충전 요청이 만료되었습니다",
  depositErrVoucherPin: "상품권 PIN을 정확히 입력해주세요 (16~18자리)",
  depositErrVoucherDup: "동일한 PIN을 여러 번 시도했습니다 · 수동 확인이 필요합니다",
  depositErrUpload: "영수증 업로드에 실패했습니다",
  depositErrDuplicate: "이미 처리 중인 충전이 있습니다",
  depositErrGeneric: "잠시 후 다시 시도해주세요",
  depositNext: "다음",
  depositPrev: "이전",
  depositClose: "닫기",
  depositSubmitLocked: "처리 중입니다…",
  depositRealtimeDegraded: "실시간 연결이 불안정합니다 · 자동으로 다시 확인 중",

  // Pre-launch confidence layer
  depositResumeTitle: "진행 중인 충전이 있어요",
  depositResumeBody: "이어서 계속하시겠습니까?",
  depositResumeContinue: "이어서 진행",
  depositResumeFresh: "새로 시작",
  depositGraceChecking: "마지막 확인 중입니다…",
  depositSafeChecking: "입금 상태를 안전하게 확인 중입니다",
  depositProtectedLine: "고객님의 돈은 안전하게 보호되고 있습니다",

  // Operational polish
  depositDeltaPreview: "PHON 반영 예정",
  depositTimelineStep1: "신청됨",
  depositTimelineStep2: "확인중",
  depositTimelineStep3: "반영완료",
  depositLastChecked: "마지막 확인 시각",
  depositInputsLocked: "금액·수단 변경은 잠겼습니다",

  // Navigation guard
  depositLeaveConfirm: "진행 중인 충전이 있습니다. 정말 나가시겠습니까?",
  depositLeaveStay: "계속 진행",
  depositLeaveExit: "나가기",

  // §14-5 Emergency Degrade Mode (PR-I)
  degradeBannerOn: "지금 시스템 보호 모드입니다 — 안심하세요, 입출금은 정상입니다",
  degradeBannerOff: "정상 모드로 돌아왔습니다",
  degradeBannerReasonDefault: "잠시 후 자동 복구됩니다",
  degradeAdminTitle: "🛡 비상 절전 모드",
  degradeAdminDesc: "화면 효과를 모두 끄고 시스템을 가볍게 만듭니다. 입출금·베팅은 영향 없습니다.",
  degradeConfirmOn: "정말 비상 절전 모드를 켤까요? 화면 애니메이션이 꺼집니다",
  degradeConfirmOff: "정상 모드로 돌아갈까요?",
  // PR-J: realtime warm-tone messages (50-70대 친화)
  realtimeReconnecting: "잠시만요, 다시 연결하고 있어요…",
  realtimeDegraded: "실시간 연결이 잠시 느려졌어요. 돈과 데이터는 안전합니다",
  realtimeRestored: "다시 실시간으로 연결됐어요",

} as const;

export type GlossaryKey = keyof typeof G;
