export * from "./types";
export { useDuelRooms, useDuelRoom } from "./hooks/useDuelRoom";
export { useFomoOracle } from "./hooks/useFomoOracle";
export { useDuelTick } from "./hooks/useDuelTick";
export { useOddsEngine } from "./hooks/useOddsEngine";
export { useSpectatorSync, type Arrival } from "./hooks/useSpectatorSync";
export { rollHmac, randomSeed, sha256Hex } from "./engine/rng";
export { computeThreshold } from "./engine/dynamicThreshold";
export { detectNearMiss, nearMissEase, strongNearMissIntensity } from "./engine/nearMiss";
export { computeFomo, rewardTierFromRoll, REWARD_LABEL, HEAT_LABEL } from "./engine/fomo";
export { computeOdds, poolImbalance, settlePayout, HOUSE_EDGE, type PoolState, type BetRecord } from "./engine/odds";
